Add class UBERON:8410004 jejuno-ileal junction
obophenotype/uberon pull request #1712
Opened 2020-12-23 14:21 UTC by paolaroncaglia

Addresses #1662

2021-01-13 15:04 UTC, dosumis requested changes
publication xrefs -> def xrefs

2021-01-14 10:59 UTC, paolaroncaglia commented
@dosumis 

> publication xrefs -> def xrefs

Done, thanks.

2021-01-25 17:50 UTC, dosumis commented on uberon_edit.obo
> +xref: https://doi.org/10.1016/B978-1-4377-2206-2.00068-3
Please move to def xrefs as DOI:10.1016/B978-1-4377-2206-2.00068-3

2021-01-25 17:50 UTC, dosumis requested changes
see comment on DOI

2021-02-01 10:11 UTC, closed without merging