Add subset tag and synonym type to UBERON:8410010
obophenotype/uberon pull request #1770
Opened 2021-02-01 10:54 UTC by paolaroncaglia

Addresses #1665

2021-02-01 10:57 UTC, paolaroncaglia commented
Hi @dosumis ,
I added the HCA subset tag, and also synonym type property = plural to 2 existing synonyms while I was there. 
Now ready for your review please.

2021-02-05 10:47 UTC, dosumis requested changes
See comments

2021-02-05 10:47 UTC, dosumis commented on uberon_edit.obo
> +property_value: added_for_HCA "" xsd:string
See comment on inguinal skin region.

2021-02-05 10:47 UTC, dosumis commented on uberon_edit.obo
> +synonym: "fimbriae of uterine tube" EXACT [] {http://purl.obolibrary.org/obo/uberon/core#PLURAL=""}
Looks like some error in how this was added.

Should be like this.
![image](https://user-images.githubusercontent.com/112839/107023912-331e0b00-679f-11eb-8580-7de0c4e352a5.png)

2021-02-05 15:37 UTC, paolaroncaglia commented
@dosumis 
I fixed the subset tag, but I can't get the synonym type (plural) to be displayed as you suggested. I need to get through more pull request reviews now, so I left the synonyms as exact, and I'll make a note to look into this again at another time please.

2021-02-05 16:09 UTC, dosumis approved these changes

2021-02-05 16:09 UTC, merged