Issue 1670
obophenotype/uberon pull request #1777
Opened 2021-02-03 15:27 UTC by paolaroncaglia

2021-02-03 15:33 UTC, paolaroncaglia commented
@dosumis 
Could we squeeze this one in too, please? The term request has been there for some time... thanks!

2021-02-05 11:37 UTC, dosumis requested changes
All look good.  Just need to fix added_for_HCA tags - need to be correct for HCAO build 
https://ontology-development-kit.readthedocs.io/en/latest/NewSlimTerm.html

2021-02-05 16:23 UTC, paolaroncaglia commented
@dosumis 
Subsets are now fixed. Ready to merge please.

2021-02-11 13:56 UTC, dosumis approved these changes

2021-02-11 13:56 UTC, merged