adding patellar surface / trochlea of femur (#1894)
obophenotype/uberon pull request #1895
Opened 2021-06-02 00:23 UTC by megbalk

issue #1894

2021-07-23 18:14 UTC, nicolevasilevsky approved these changes

2021-07-25 16:05 UTC, dosumis requested changes
Add classification

2021-07-25 16:05 UTC, dosumis commented on src/ontology/uberon-edit.obo
> +relationship: part_of UBERON:0004406 ! distal epiphysis of femur
add 

is_a: surface of bone

2021-07-26 17:00 UTC, megbalk commented on src/ontology/uberon-edit.obo
> +relationship: part_of UBERON:0004406 ! distal epiphysis of femur
done.

2021-07-26 19:23 UTC, dosumis approved these changes

2021-07-27 09:54 UTC, merged