add term UBERON:8000008 cementocyte lacuna
obophenotype/uberon pull request #2015
Opened 2021-08-02 19:50 UTC by nicolevasilevsky

close #1397

2021-08-03 16:47 UTC, cmungall requested changes

2021-08-03 16:47 UTC, cmungall commented on src/ontology/uberon-edit.obo
> +relationship: part_of UBERON:0001753 ! cementum
no isa

2021-08-03 16:54 UTC, cmungall commented
not a blocker, but when doing something like this, you should be thinking: I see a CL class mentioned in the text? What is the relationship between the cell and the structure? part-of? located-in? has-soma-located-in? 

Also, are there commonalities between cementoblast-cementum lacunae relationships and the relationships between osteoblasts and lacunae in bones?

it can help future maintenance of the ontology tremendously if things are viewed holistically like this. otherwise we will have one curator making statements about one set of structures, and another about a homologous set of structures, both correct, but different perspectives, leading it confusion and inconsistency

2021-08-03 17:02 UTC, nicolevasilevsky commented
should we add a new term for lacuna?
https://en.wikipedia.org/wiki/Lacuna_(histology)

2021-08-03 17:02 UTC, nicolevasilevsky commented on src/ontology/uberon-edit.obo
> +relationship: part_of UBERON:0001753 ! cementum
added is_a 'anatomical cavity'

2021-08-03 17:06 UTC, nicolevasilevsky commented
I think a cementoblast is located in the cementocyte lacuna. Would this be added to Uberon or CL?

From [wikipedia](https://en.wikipedia.org/wiki/Cementoblast):
Thus cementoblasts resemble bone-forming osteoblasts but differ functionally and histologically. The cells of cementum are the entrapped cementoblasts, the cementocytes. **Each cementocyte lies in its lacuna (plural, lacunae),** similar to the pattern noted in bone. These lacunae also have canaliculi or canals. Unlike those in bone, however, these canals in cementum do not contain nerves, nor do they radiate outward. Instead, the canals are oriented toward the periodontal ligament (PDL) and contain cementocytic processes that exist to diffuse nutrients from the ligament because it is vascularized.[3] The progenitor cells also found in the PDL region contribute to the mineralization of the tissue.[4]

2021-08-03 17:08 UTC, nicolevasilevsky commented
> Also, are there commonalities between cementoblast-cementum lacunae relationships and the relationships between osteoblasts and lacunae in bones?

From what I just read, yes, I think this relationship is the same. We don't have the term lacunae in Uberon, but this is described in the definition of 'bone tissue':

Skeletal tissue with a collagen-rich extracellular matrix vascularized, mineralized with hydroxyapatite and typically including osteocytes located in lacunae that communicate with one another by cell processes (in canaliculi). Bone is deposited by osteoblasts.

2021-09-09 02:22 UTC, cmungall approved these changes

2021-09-30 19:34 UTC, merged