Make the mappings file into a proper component
obophenotype/uberon pull request #2178
Opened 2021-11-22 11:55 UTC by anitacaron

Fixes #2166

2021-11-22 13:54 UTC, gouttegd commented on src/ontology/uberon.Makefile
> +$(OTHER_SRC): mappings/fbbt-mappings.sssom.tsv ../scripts/sssom2xrefs.awk
This is not future-proof. This works for now while `mappings.owl` is the only component, but won‘t work anymore if/when we add another component in the future.

I think it’s fine here to leave that rule as it were; that is, keep referring to the mappings component directly by its filename, not through the `OTHER_SRC` variable.

2021-11-22 14:11 UTC, matentzn commented on src/ontology/uberon.Makefile
> -	$(OWLTOOLS) --no-logging $< $(COMPONENTSDIR)/disjoint_union_over.ofn issues/contributor.owl --merge-support-ontologies --merge-import http://purl.obolibrary.org/obo/uberon/components/mappings.owl --
Double chec SRCMERGED has OTHER_SRC dependency

2021-11-22 16:13 UTC, gouttegd commented on src/ontology/uberon.Makefile
> -	$(OWLTOOLS) --no-logging $< $(COMPONENTSDIR)/disjoint_union_over.ofn issues/contributor.owl --merge-support-ontologies --merge-import http://purl.obolibrary.org/obo/uberon/components/mappings.owl --
@matentzn Surprisingly, `SRCMERGED` is _not_ dependent on `OTHER_SRC` in the standard, ODK-generated Makefile. This is something that should ultimately be fixed in the ODK itself.

2021-11-22 16:23 UTC, gouttegd commented on src/ontology/uberon.Makefile
> -	$(OWLTOOLS) --no-logging $< $(COMPONENTSDIR)/disjoint_union_over.ofn issues/contributor.owl --merge-support-ontologies --merge-import http://purl.obolibrary.org/obo/uberon/components/mappings.owl --
The `--merge-support-ontologies` has nothing to do with the subsequent `--merge-import` and is needed here to make sure the `disjoint_union_over.ofn` and `contributor.owl` are merged.

2021-11-22 16:26 UTC, gouttegd requested changes
To change:

- [ ] Add back the `--merge-support-ontologies` in `uberon.Makefile` line 95;
- [ ] Re-replace `$(OTHER_SRC)` by `$(COMPONENTSDIR)/mappings.owl` in `uberon.Makefile` line 1173

2021-11-23 12:35 UTC, gouttegd approved these changes

2021-11-23 13:45 UTC, merged