Add a new inSubset ROBOT template
obophenotype/uberon pull request #2196
Opened 2021-11-26 19:54 UTC by rays22

This commit intends to add a new `inSubset` ROBOT template.
This commit is related to https://github.com/obophenotype/uberon/issues/2127#issuecomment-979791339 .

2022-02-11 11:44 UTC, dosumis commented
I think this would work nicely.  We need to delete the example before merging though.  Also @nicolevasilevsky what AP are we now using for linking to tickets dc:source or rdfs:seeAlso ?  (seems like something should have in our new centralised editor's guide).

2022-02-11 11:47 UTC, dosumis reviewed
Activating template will also require adding OWL file it produces to components + import statement on uberon-edit.owl

2022-02-11 11:47 UTC, dosumis commented on src/templates/in-subset.template.tsv
> +EXAMPLE:0000000	never_in_euarchontoglires	https://github.com/obophenotype/uberon/issues/????
Delete example line.

2022-02-28 14:29 UTC, matentzn commented
@rays22 can you finish and merge this PR?

2022-03-02 10:42 UTC, rays22 commented on src/templates/in-subset.template.tsv
> +EXAMPLE:0000000	never_in_euarchontoglires	https://github.com/obophenotype/uberon/issues/????
Done.

2022-03-02 10:44 UTC, rays22 commented
> Activating template will also require adding OWL file it produces to components + import statement on uberon-edit.owl

@dosumis ,
Do I need to do that before merging?

2022-03-02 10:49 UTC, matentzn commented
Best put this PR on our meeting agenda and I will tell you how to create a ROBOT template component with ODK!

2022-03-02 16:17 UTC, nicolevasilevsky commented
we use rdfs:seeAlso in Mondo

2022-03-07 14:12 UTC, shawntanzk commented
1) Create new component 
2) Have component dependent on tsv template 
3) component = template cmd that turns template into owl 

@shawntanzk  to point @rays22 to docs and fix up docs whie at it

2022-03-07 14:14 UTC, shawntanzk commented
Currently doesnt seem like there is documentation on components - @shawntanzk to work on documentation for this

2022-03-07 16:13 UTC, shawntanzk commented
docs: https://github.com/obophenotype/uberon/pull/2339

2022-03-15 18:16 UTC, rays22 commented
> linking to tickets dc:source or rdfs:seeAlso

FYI: This template uses `oio:source` instead of `rdfs:seeAlso` for provenance **at the annotation level** as discussed here:
<https://github.com/obophenotype/uberon/pull/2108#issuecomment-947621119>

2022-03-16 16:36 UTC, shawntanzk commented
@rays22 I'm a bit confused, the tsv you added is for inSubset, but you activated in-taxon template?

2022-03-16 16:38 UTC, shawntanzk commented on src/ontology/uberon-odk.yaml
> +    - filename: in-taxon.owl
should this be in-subset.owl?

2022-03-16 16:44 UTC, rays22 commented on src/ontology/uberon-odk.yaml
> +    - filename: in-taxon.owl
Yes, you are right.

2022-03-16 16:50 UTC, rays22 commented on src/ontology/uberon-odk.yaml
> +    - filename: in-taxon.owl
Fixed.

2022-03-16 16:59 UTC, shawntanzk commented
@rays22 you need to run `sh run.sh update_repo` after the change in the yaml file

2022-03-16 21:01 UTC, matentzn approved these changes

2022-03-16 21:06 UTC, matentzn approved these changes

2022-03-16 21:06 UTC, matentzn commented on src/ontology/components/in-taxon.owl
> +<?xml version="1.0"?>
wrong name, should be `in-subset.owl`

2022-03-16 21:06 UTC, matentzn commented on docs/odk-workflows/RepositoryFileStructure.md
> +| in-taxon.owl | None |
is-subset.owl

2022-03-16 21:07 UTC, matentzn requested changes
Sorry in-subset.owl not `in-taxon.owl`.

2022-03-16 21:46 UTC, matentzn approved these changes

2022-03-17 06:58 UTC, merged