Add vasculature template
obophenotype/uberon pull request #2209
Opened 2021-12-14 16:10 UTC by anitacaron

Related to https://github.com/hubmapconsortium/ccf-validation-tools/issues/120

2021-12-14 17:52 UTC, dosumis commented
Converting to draft for now as we need to discuss whether adding connected_to relationships is the best approach for these.

2022-01-26 17:32 UTC, dosumis requested changes
* I don't think vasculature.owl should be committed
* Maybe robot templates need to be enabled in ODK to build components/vasculature_class.owl?
* Value for >AI should be full IRI (or CURIE might also work) - this looks like just string

2022-01-26 19:10 UTC, anitacaron commented
I followed this doc to include the template. https://github.com/obophenotype/uberon/tree/master/src/templates 
Enabling `use_custom_import_module` will create `external_import.tsv` with a list of terms to import when the imports are refreshed. (found here the doc https://github.com/OBOFoundry/COB/blob/53368763cd61e871543bfb8836aee8917cab8bc2/docs/odk-workflows/UpdateImports.md#using-the-custom-import-template) Is this what you hope to get?

2022-01-27 10:27 UTC, dosumis commented
I think this is happening because the import statement is looking for a file in components that you've committed in templates
![image](https://user-images.githubusercontent.com/112839/151339982-094aeccb-bc60-4b3a-b414-950b3a8d69aa.png)

I guess the make command doesn't move it into place? @matentzn  - is there a gap in the docs?

> Enabling use_custom_import_module will create external_import.tsv with a list of terms to import when the imports are refreshed. (found here the doc https://github.com/OBOFoundry/COB/blob/53368763cd61e871543bfb8836aee8917cab8bc2/docs/odk-workflows/UpdateImports.md#using-the-custom-import-template) Is this what you hope to get?

This is not relevant (we're not doing anything with imports).   I was just speculating that it might be possible to configure ODK to rebuild from robot templates & save the file to components automatically.

2022-01-28 10:31 UTC, matentzn commented
Didnt read all your comments, just fixed the catalog (see last commit). Was that all you need from me?

2022-01-28 10:32 UTC, matentzn commented
Remember @anitacaron catalog.xml is relative path from `src/ontology`, not `src/`.

2022-01-28 10:49 UTC, anitacaron commented
Thanks, @matentzn! 

Do we need to add `vasculature_class.owl`, or it will be generated when running `prepare_release`?

2022-01-28 10:52 UTC, matentzn commented
You need it, if you want it to be seen when opening uberon-edit.obo

2022-01-28 10:53 UTC, matentzn commented on src/ontology/uberon-edit.obo
> +import: http://purl.obolibrary.org/obo/uberon/components/vasculature_class.owl
@anitacaron if you add this, the owl file has to exist as well! So yes, leave it checked in here as is!

2022-01-28 13:42 UTC, anitacaron commented on src/templates/vasculature_class.owl
> +        <oboInOwl:inSubset rdf:resource="&lt;http://purl.obolibrary.org/obo/uberon/core#human_reference_atlas&gt;"/>
@dosumis it was already good before changing to the complete URI; somewhere it's already defined (?)

2022-01-28 13:43 UTC, anitacaron commented on src/templates/vasculature_class.owl
> +        <oboInOwl:inSubset rdf:resource="&lt;http://purl.obolibrary.org/obo/uberon/core#human_reference_atlas&gt;"/>
I'll revert the commit.

2022-02-07 10:34 UTC, dosumis approved these changes

2022-02-07 10:35 UTC, merged