Create lower_tooth_pattern.yaml
obophenotype/uberon pull request #2467
Opened 2022-05-11 21:03 UTC by megbalk

Similar to the upper_tooth_pattern.yaml (see [PR](https://github.com/obophenotype/uberon/pull/2231)), this would create a pattern for the lower teeth

2022-08-26 15:33 UTC, megbalk commented
pattern for naming teeth: 
“Secondary upper right first molar tooth”

2022-10-13 23:57 UTC, megbalk commented
@nicolevasilevsky I'm not sure what the next steps are

2022-10-14 11:47 UTC, rays22 requested changes
* I have added suggestions of how to fix the QC errors.
* It is not obvious to me from the information in the PR what the anatomical justifications are for replacing `lower_teeth_pattern.yaml` with `lower_tooth_pattern.yaml`.

2022-10-14 11:47 UTC, rays22 commented on src/patterns/dosdp-patterns/lower_tooth_pattern.yaml
> +  syn: "xsd:string"
```suggestion
  your_syn: "xsd:string"
```
This is to fix QC error:

```
/usr/local/lib/python3.10/dist-packages/dosdp/validator.py:68: UserWarning:annotations.[0].vars has values ({'your_syn'}) not found in pattern variable list ({'dentition', 'syn', 'xrefs', 'jaw', 'tooth'}): 
```

2022-10-14 11:47 UTC, rays22 commented on src/patterns/dosdp-patterns/lower_tooth_pattern.yaml
> +  # A secondary dentition molar tooth 1 that is part of a lower jaw region
```suggestion
  # A secondary dentition molar tooth 1 that is part of a lower jaw region
  vars:
    - dentition
    - tooth
```
This is to fix QC error:

```
/usr/local/lib/python3.10/dist-packages/dosdp/validator.py:30: UserWarning:{'text': 'A %s %s that is part of a lower jaw region.', 'annotations': [{'annotationProperty': 'xref', 'value': 'xrefs'}]} is not valid under any of the given schemas
```

2022-10-14 11:47 UTC, rays22 commented on src/patterns/dosdp-patterns/upper_tooth_pattern.yaml
> +  syn: "xsd:string"
```suggestion
  your_syn: "xsd:string"
```
This is to fix an error.

2022-10-20 08:45 UTC, rays22 approved these changes

2022-10-20 18:23 UTC, merged