Polysemy: trochlea of femur. Obsolete offending UBERON:7500077
obophenotype/uberon pull request #2506
Opened 2022-05-30 11:17 UTC by vasvir

This PR tries to resolve the 3 of 4 of the issues mentioned in #2424

The problem that is addressed here is that

"trochlea of femur" (UBERON:7500077) is an exact synonym to "intercondylar fossa" (UBERON:4200096). This creates unecessary polysemy.

The proposed solution is to obsolete UBERON:7500077 altogether.

I also moved from the obsoleted term the following:
* synonym: "patellar surface of femur" EXACT []
* is_a: UBERON:4200230 ! surface of bone
* relationship: part_of UBERON:0004406 ! distal epiphysis of femur

Tagged @chandron, @elekka since he helped with the biology.

Tagged @matentzn as requested.

2022-05-30 11:19 UTC, matentzn requested changes

2022-05-30 11:19 UTC, matentzn commented on src/ontology/uberon-edit.obo
> +replaced_by: UBERON:UBERON:4200096
Just `UBERON:4200096`

2022-05-30 12:18 UTC, vasvir commented
Thanks for the heads up. I believe I fixed it now (after a brief git 101 detour).

2022-05-30 12:21 UTC, matentzn commented
Cool, many of our curators are on vacation, they will deal with this issue here soon! Thanks :)

2022-08-09 21:22 UTC, nicolevasilevsky approved these changes
this looks good to me

2022-08-09 23:15 UTC, nicolevasilevsky commented
I don't understand why this is failing? @shawntanzk could you help or point me to someone that can? Thanks!

2022-08-10 06:47 UTC, vasvir commented
I would also like to be enlightened here. It fails in "post_comment / Post reasoned post_comment" and at least one of my previous PR had the same issue. So it would be great to understand:

Is this a problem of the a) PR or with the b) CI?

If a) how to fix?

Thanks

2022-08-10 07:09 UTC, shawntanzk commented
@nicolevasilevsky & @vasvir looks like a github token issue I think - might be something we overlooked @ubyndr, if someone doesn't have the right permissions and they create the PR, it might be an issue. 
Btws don't worry too much about it, that is just to create and post a human readable diff to the ticket, as long as ontology_qc passes, its safe :)

2022-08-11 15:40 UTC, nicolevasilevsky commented
@shawntanzk is this okay to merge then? thanks!

2022-08-11 15:54 UTC, shawntanzk commented
> @shawntanzk is this okay to merge then? thanks!

Didn't look at content, but QC wise its good to merge :)

2022-08-11 16:08 UTC, nicolevasilevsky commented
I will merge!

2022-08-11 16:08 UTC, merged