Change ganglion's parent
obophenotype/uberon pull request #2626
Opened 2022-08-19 15:18 UTC by anitacaron

Related to https://github.com/obophenotype/uberon/issues/2495#issuecomment-1187364719

2022-08-19 15:50 UTC, shawntanzk commented
> or we could just generalise to the parent class (I'm sure very many ganglia also have whole cells).

Had the same thought - I think it can't be multi cell part structure as it would have complete cells as a part. Maybe broader to anatomical cluster?

2022-09-04 10:35 UTC, dosumis commented
(Sorry for slow response.  I actually wrote a response on this some time ago, but now realised I didn't post it - trying to reconstruct my argument here).

General issue: granularity constraints on super general/abstract classes used across species are a bad idea.  They will almost inevitable lead to problems like this, where we spend time arguing over things that few, if any biologists care about (see [The Pici principle](https://www.russet.org.uk/blog/2011/10/the-pici-principle-what-you-should-not-say/)).  Even granularity constraints on much more specific classes can cause problems across species, e.g.  2 structures  (muscles, sensory structures, glands) may be homologous across insects but consist of  a single cell in some species, and a small cluster of cells in others.  

Specific issue: If you look at both the official Uberon  test def and the external definitions  that uberon aggregates, they all emphasise that consisting of (mostly/primarily) an aggregation of neuronal cell bodies (soma) is important.  But none of them say that whole cells are not present.  The first of the external definitions could cover a whole arthropod brain, which has lots of whole cells, including neurons.  OTOH I know of a few uses in insects which refer entirely to an aggregation of neuronal cell bodies (see ['dorsal organ ganglion'](https://www.ebi.ac.uk/ols/ontologies/fbbt/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBbt_00007227)).

Conclusion: push the term up under 'anatomical structure'.  Consider the same approach in general when we encounter these problems in Uberon.  The only argument against is that browsing a flattened structure is harder, but I think that argument is bogus too:  If we can't decide where these classes should live, why should we expect users to know which branch to find them in while browsing.

2022-09-04 10:37 UTC, dosumis requested changes
Please move up under 'anatomical structure'.  That way we are unlikely to be back here discussing this issue again.  See comment for details.

2022-09-05 13:37 UTC, dosumis approved these changes

2022-09-05 15:53 UTC, merged