add part of to 'preorbital bone region' structures
obophenotype/uberon pull request #2942
Opened 2023-06-23 13:16 UTC by shawntanzk

Fixes https://github.com/obophenotype/uberon/issues/2936
Note, did not do much research, just following definition as suggested by @aleixpuigb 
Honestly just had a bit of time between finish my last task and drinks so... lol  
#gogoeditdiff

2023-06-23 13:46 UTC, aleixpuigb commented
Hi @megbalk and @helenamachado, I would like to ask your opinion about this ticket since you added this term in #2416. Given the definition, would it be ok to add the axiom `'part of' some 'preorbital bone region'` to `jugal bone`, `lacrimal bone` and `maxilla`?

2023-06-26 08:07 UTC, megbalk commented
@aleixpuigb yep! For maxilla, it is only the part anterior to the orbit. I suppose it could be also added for nasal bones, but only sometimes as it depends on the location of the nasal bones.

2023-06-26 08:14 UTC, aleixpuigb commented on src/ontology/uberon-edit.obo
> +relationship: part_of UBERON:7500102 ! preorbital bone region
I suggest 'overlaps' instead of 'part of'

2023-06-26 08:15 UTC, aleixpuigb requested changes
Please, see inline comment.

2023-06-26 08:40 UTC, shawntanzk commented
#gogoeditdiff

2023-06-26 08:42 UTC, shawntanzk commented
thanks @aleixpuigb & @megbalk - not sure if the other part_of are alright, but I have changed the one you pointed out as suggested. Also realised automated diff didnt run - I dont think there will be any issue, but in case, would be more comfortable letting that run and making sure nothing weird is inferred from these additions

2023-06-26 09:29 UTC, aleixpuigb approved these changes

2023-06-26 10:59 UTC, merged