Import OMO terms
obophenotype/uberon pull request #3092
Opened 2023-10-13 16:18 UTC by anitacaron

Fixes #3058

Updated `imports/merged_import.owl` with OMO:0003004 and OMO:0003000.

2023-10-13 17:03 UTC, matentzn commented
Ehm.. a bit too much.. the diff.

2023-10-13 18:08 UTC, gouttegd commented
The diff is huge because _many_ terms are removed from the import module (especially a bunch of GO terms). Not sure why.

It may have been a glitch of some sort, because I just tried running `refresh-imports` again and all those terms are back.

2023-10-16 11:43 UTC, bvarner-ebi commented on src/ontology/imports/omo_terms.txt
> +
Can OMO:0003011 be added?

2023-10-24 09:36 UTC, anitacaron commented on src/ontology/imports/omo_terms.txt
> +
Yes, I'll add it.

2023-10-26 08:54 UTC, anitacaron commented
@matentzn @gouttegd could you review, please?

2023-10-26 09:37 UTC, gouttegd requested changes
I see no problems _in the final state_ of the PR. However I advise against merging it as it is.

In commit 2a10fb6 a lot of terms were removed from the `merged_import.owl` module; then in the more recent 3240ea7 commit, all those terms were added back. I am not sure why this happened, but there must have been a glitch in the import pipeline when the files that were committed in 2a10fb6 were generated.

So now the final state of `merged_import.owl` is good, but having two “opposite” commits (one that removes ~100K lines for nothing, and then a second that adds those ~100K lines back) would needlessly pollute the history and I advise against that.

Either:
* resubmit a clean PR without the “removal-then-reinsertion” dance, or
* at the very least make a “squash” merge.

2023-10-26 09:39 UTC, gouttegd approved these changes

2023-10-26 09:41 UTC, anitacaron commented
Yes, `squash and merge` is the default option when merging a PR.

2023-10-26 09:42 UTC, anitacaron commented
Thanks, Damien.

2023-10-26 09:43 UTC, merged

2023-10-26 09:46 UTC, anitacaron commented
I'm not sure.

2023-10-26 10:44 UTC, matentzn commented
This is configured at GitHub project level

2023-10-26 10:46 UTC, gouttegd commented
But then how comes that it does not apply to me? When I merge a PR on Uberon, for me the default option is always a “normal” merge, _not_ a “squash” one.