Obsolete and merge a handful of redundant terms
obophenotype/uberon pull request #3196
Opened 2024-01-29 16:15 UTC by gouttegd

This PR obsoletes a few terms that are redundant with other terms:

* 'optic eminence surface ectoderm' (#3156),
* 'vitelline venous plexus' (#3157),
* 'thymus subunit' (#3158),
* 'gland of anal sac' (#3159),
* 'telencephalic tracts' (#3160),
* 'common crus' (#3161).

2024-02-14 15:51 UTC, aleixpuigb requested changes
Please, see inline comments.
The instructions in obo academy on obsoleting terms do not ask to introduce URL in replaced_by as IRI, I need to edit it and create a ticket to change all incorrect of obsoleted terms in Uberon, [similar to CL](https://github.com/obophenotype/cell-ontology/pull/2273).

2024-02-14 15:51 UTC, aleixpuigb commented on src/ontology/uberon-edit.obo
> +property_value: term_tracker_item "https://github.com/obophenotype/uberon/issues/3159" xsd:anyURI
Please, change the format of this URL to IRI.

2024-02-14 15:51 UTC, aleixpuigb commented on src/ontology/uberon-edit.obo
> +replaced_by: UBERON:0004760
Please, consider to add 'gland of anal sac' as a synonym to 'gland of anal canal'.

2024-02-14 17:38 UTC, gouttegd commented on src/ontology/uberon-edit.obo
> +property_value: term_tracker_item "https://github.com/obophenotype/uberon/issues/3156" xsd:anyURI
Doing so result in the annotation being interpreted as a _relationship_, which violates one of the CI checks that tries to enforce that an obsolete term should have no relationships.

Who decided that the value of `term_tracker_item` should be an IRI anyway, and why was the tech group not consulted? This is going to be an issue for any ontology that uses the OBO format as its edit format.

2024-02-14 20:42 UTC, gouttegd commented on src/ontology/uberon-edit.obo
> +property_value: term_tracker_item "https://github.com/obophenotype/uberon/issues/3156" xsd:anyURI
Correction: This may not be an issue for “any ontology that uses the OBO format” – merely for those that do the same kind of CI checks as Uberon.

2024-02-15 09:05 UTC, anitacaron commented on src/ontology/uberon-edit.obo
> +property_value: term_tracker_item "https://github.com/obophenotype/uberon/issues/3156" xsd:anyURI
Technically, we want to ensure only URLs are added in `term_tracker_item`. But I agree that the issue is in the OBO Format.

2024-02-15 11:03 UTC, gouttegd commented on src/ontology/uberon-edit.obo
> +property_value: term_tracker_item "https://github.com/obophenotype/uberon/issues/3156" xsd:anyURI
And what is the problem with storing URLs as literal URLs (xsd:anyURI)? Why insisting that they should be IRIs?

2024-02-15 11:06 UTC, gouttegd commented on src/ontology/uberon-edit.obo
> +property_value: term_tracker_item "https://github.com/obophenotype/uberon/issues/3156" xsd:anyURI
In any case, either “we” drop this requirement that `term_tracker_item` should be IRIs, or “we” need to either update our CI checks to make an exception that obsolete terms can have `term_tracker_item` relationships or to update the OBO parser in the OWL API to stop interpreting IRI-valued annotations as relationships.

2024-02-15 15:39 UTC, balhoff commented on src/ontology/uberon-edit.obo
> +property_value: term_tracker_item "https://github.com/obophenotype/uberon/issues/3156" xsd:anyURI
All of the existing values for term_tracker_item in Uberon seem to be xsd:anyURI.

2024-02-16 10:42 UTC, aleixpuigb commented
Apologies for asking to change the format, it was a mistake from my part. Could you revert [the commit](https://github.com/obophenotype/uberon/pull/3196/commits/8d21d5f6881c9849ff47c556797fbd5b4c6dc552), so this PR can be merged before the next release?

2024-02-16 13:17 UTC, gouttegd commented
I’ve pushed a new clear PR (same changes but without the 8d21d5f commit) to replace this one.

2024-02-16 13:17 UTC, closed without merging