update HBA bridge mappings to nerves to point to nerve roots
obophenotype/uberon pull request #3281
Opened 2024-05-21 13:44 UTC by AvolaAmg

Fixes some #3264

@hkir-dev see if it fixes the issue on PCL

2024-05-21 14:11 UTC, anitacaron requested changes

2024-05-21 14:12 UTC, AvolaAmg commented on src/ontology/uberon-edit.obo
> +
geniune typo. I had to add trigeminal nerve root instead of trigeminal nerve development

2024-05-21 14:16 UTC, anitacaron commented on src/ontology/imports/merged_import.owl
> +AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/IAO_0000112> "example of usage"@en)
I think we need to refresh the HRA bridge, right?

2024-05-21 14:18 UTC, anitacaron commented on src/ontology/uberon-edit.obo
> +
Ok, but do you use this term in this PR? 😄

2024-05-21 14:59 UTC, hkir-dev commented on src/ontology/imports/merged_import.owl
> +AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/IAO_0000112> "example of usage"@en)
We only need to update the edit file in uberon. There's no need to modify the merged_import.owl file here.

2024-05-23 13:05 UTC, anitacaron commented on src/ontology/uberon-edit.obo
> +
It was removed.

2024-05-23 13:05 UTC, anitacaron commented on src/ontology/imports/merged_import.owl
> +AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/IAO_0000112> "example of usage"@en)
Reverted changes on this file.

2024-05-23 13:18 UTC, anitacaron commented
#gogoeditdiff

2024-05-23 16:00 UTC, hkir-dev commented
I conducted some tests, and these updates resolved the inconsistencies mentioned in issue https://github.com/brain-bican/human_brain_atlas_ontology/issues/2

2024-05-24 08:15 UTC, anitacaron commented
#gogoeditdiff

2024-05-24 11:40 UTC, anitacaron commented
#gogoeditdiff

2024-05-24 11:56 UTC, anitacaron commented
#gogoeditdiff

2024-06-10 13:45 UTC, anitacaron approved these changes

2024-06-10 13:47 UTC, anitacaron commented
I'll merge it because Alida is away, and we need a UBERON release soon.

2024-06-10 13:47 UTC, merged