Fix some ZFA mapping errors
obophenotype/uberon pull request #3361
Opened 2024-09-12 16:42 UTC by gouttegd

This PR fixes a handful of “simple” mapping errors¹ between ZFA and Uberon:

* ZFA’s '[griseum centrale](http://purl.obolibrary.org/obo/ZFA_0000518)' is remapped to Uberon’s '[central gray substance of medulla](http://purl.obolibrary.org/obo/UBERON_0002867)' (#3353);
* ZFA’s [coelom](http://purl.obolibrary.org/obo/ZFA_0001438) is remapped to Uberon’s [coelom](http://purl.obolibrary.org/obo/UBERON_0011997) (#3353);
* ZFA’s '[inferior raphe nucleus](http://purl.obolibrary.org/obo/ZFA_0000366)' is remapped to Uberon’s '[medullary raphe nuclear complex](http://purl.obolibrary.org/obo/UBERON_0002692)' (#3356).

See the linked issues (or the individual commit messages) for the rationale behind each remapping.

closes #3353 
closes #3356

---
¹ What I mean by “simple mapping error”: the error is simply that a ZFA term is mapped to the wrong Uberon term, but none of the term on either side is otherwise incorrect.

2024-10-21 16:53 UTC, gouttegd commented
PR updated to remove entirely the mapping with ZFA’s '[inferior raphe nucleus](http://purl.obolibrary.org/obo/ZFA_0000366)', as suggested in the comments of #3356.

2024-10-22 10:44 UTC, aleixpuigb requested changes
I agree with the changes in 'coelom' and the 'inferior raphe nucleus', but I think there might be a mistake in the ZFA for 'Griseum centrale'.

2024-10-22 10:44 UTC, aleixpuigb commented on src/ontology/uberon-edit.obo
> +xref: ZFA:0000518
Could it be that ZFA is not correct? [Olson et al.,](https://pmc.ncbi.nlm.nih.gov/articles/PMC6084820/) show that the 'Griseum centrale' is an homologue of the 'periaqueductal gray', which is found in the midbrain (and it is a synonym of 'central gray substance of midbrain' UBERON:0003040). This is also stated by [Blasiak et al](https://www.frontiersin.org/journals/molecular-neuroscience/articles/10.3389/fnmol.2022.984524/full). Therefore, I think that the maping is correct, but the ZFA textual and logical definition are not.

2024-10-23 09:35 UTC, aleixpuigb commented on src/ontology/uberon-edit.obo
> +xref: ZFA:0000518
> I think at this point, regardless of where the 'griseum centrale' really is in Zebrafish (hindbrain, as ZFA says, or midbrain?), the only sensible action for Uberon is to remove the mapping entirely. Better not to assert anything than to assert something dubious.

I agree, the literature is too conflictive in this case.

2024-10-23 09:36 UTC, aleixpuigb approved these changes

2024-10-23 09:44 UTC, merged