NTR Thalamus
obophenotype/uberon pull request #3432
Opened 2024-11-22 14:57 UTC by AvolaAmg

Fixes #3171

2024-11-22 14:58 UTC, AvolaAmg commented
#gogoeditdiff

2024-11-23 17:58 UTC, cmungall requested changes
How is this different from the existing term "dorsal plus ventral thalamus"? Perhaps this could be renamed (the name is awkward, this was intentional due to terminological ambiguity of "thalamus")

2024-11-28 13:23 UTC, dosumis requested changes

2024-11-28 13:23 UTC, dosumis commented on src/ontology/uberon-edit.obo
> +def: "The thalamus is composed by two grey matter structure of the diencephalon one in each hemisphere. It is located in the center of the brain, above the mesencephalon and the midbrain. The thalamu
Add species qualification on details - e.g. in primates it is compose of 50-60 nuclei...

2025-01-06 23:43 UTC, cmungall commented
@AvolaAmg - see my comments above, what are your thoughts on the need for a new concept vs renaming the existing one?

2025-08-01 06:13 UTC, cmungall commented on src/ontology/uberon-edit.obo
> +is_a: UBERON:0010225 ! thalamic complex
even if we needed a new term this would not be is-a

2025-08-01 06:13 UTC, cmungall commented
no new term needed, see issue

2025-08-01 06:13 UTC, closed without merging

2025-08-06 08:47 UTC, dosumis commented
Hmm - Still need clear synonyms/guidance for use in annotating mammals. That was the motivating factor here CC @RiveraAndrea83